### ISSUE TITLE
Milestone 0.1.0 - Genesis

### ISSUE THREAD

**Issue by marceloboeira** [14bits/voik#7]
Let's handle this issue as a discussion forum for the first milestone

IMO, these are the things we should aim for our first MVP.

### 1. Storage

  * [ ] Core CommitLog
    * [ ] Segments
      * [x] ~Write to segments~
      * [x] ~Write across segments~
      * [x] ~Read from segment~
      * [x] ~Read across segments~
        * [x] Index
        * [x] ~Better API for reading~ (#5) Thanks @cuichenli 
          * [x] ~Record Struct~
            * [x] ~End-to-end use of records~
      * [x] ~Extract logfile from segment~
      * [x] ~Memory Mapped IO~
        * [x] ~Write~
          * [x] ~Index~
          * [x] ~Segment~
          * [x] ~Refactor segment split to take index into account~
        * [x] ~Read~
          * [x] ~Index~
          * [x] ~Segment~
      * [ ] Restore state from disk (#4)
    
### 2. Networking
* [ ] Networking/API (#6)
  * [ ] Decide simple inicial protocol
  * [ ] Implement Basic Socket Communication
  * [ ] Implement TCP/HTTP?
  * [ ] Write to streams over the network
  * [ ] zero-cost copy (OS sendfile)

### 3. Operational
* [ ] Operational
  * [ ] Configuration
      * [ ] CLI Basics

We'll leave replication out of the first Milestone.

--------------------------------------

### Extra

* [x] ~CI/Tooling~
  * [x] ~Setup Travis~
    * [x] ~Build with Linux/macOS~
  * [ ] Docker
    * [ ] Alpine
* [ ] Consistency Testing (#8)
* [ ] Benchmarks (#10)

**Comment by cuichenli** [comment]
I’m glad to have helped 😄 . I will also have a look at other issues. Also thanks for the good opportunity to let me contribute and learn.

**Comment by alis93** [comment]
Hi,

Really interesting project you've got here and would really be interested in contributing. Been looking at some issues and wondering if you had anything you'd like me to work on.

Both restoring state from disk #4  and Consistency integration test #8 seemed to catch my eye.

Let me know if I can work on either of these and I'll get to work on them.
